language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "aimobier
  - git config user.email "200739491@qq.com
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${github}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - make-blog
env:
 global:
   - GH_REF: github.com:aimobier/aimobier.github.io.git
